<option value="allergy & immunology">Allergy & Immunology</option>
<option value="anesthesiology">Anesthesiology</option>
<option value="dermatology">Dermatology</option>
<option value="Diagnostic Radiology">Diagnostic Radiology</option>
<option value="Emergency Medicine">Emergency Medicine</option>
<option value="Family Medicine">Family Medicine</option>
<option value="Internal Medicine">Internal Medicine</option>
<option value="Medical Genetics">Medical Genetics</option>
<option value="Neurology">Neurology</option>
<option value="Nuclear Medicine">Nuclear Medicine</option>
<option value="Obstetrics & Gynecology">Obstetrics and Gynecology</option>
<option value="Ophthamology">Ophthamology</option>
<option value="Pathology">Pathology</option>
<option value="Paediatrics">Paediatrics</option>
<option value="Physical Medicine & Rehabilitation">Physical Medicine & Rehabilitation</option>
<option value="Preventive Medicine">Preventive Medicine</option>
<option value="Psychiatry">Psychiatry</option>
<option value="Radiation Oncology">Radiation Oncology</option>
<option value="Surgery">Surgery</option>
<option value="Urology">Urology</option>
